In [91]:
from scipy.io import arff
import pandas as pd

In [92]:
data = arff.loadarff('4year.arff')
df = pd.DataFrame(data[0])

In [93]:
df['bankruptcy'] = (df['class'] == b'1')

In [94]:
df.head()

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,Attr11,Attr12,Attr13,Attr14,Attr15,Attr16,Attr17,Attr18,Attr19,Attr20,Attr21,Attr22,Attr23,Attr24,Attr25,Attr26,Attr27,Attr28,Attr29,Attr30,Attr31,Attr32,Attr33,Attr34,Attr35,Attr36,Attr37,Attr38,Attr39,Attr40,Attr41,Attr42,Attr43,Attr44,Attr45,Attr46,Attr47,Attr48,Attr49,Attr50,Attr51,Attr52,Attr53,Attr54,Attr55,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,class,bankruptcy
0,0.159290,0.46240,0.07773,1.1683,-44.853,0.467020,0.189480,0.82895,1.1223,0.38330,0.189480,0.41025,0.155480,0.189480,771.49,0.47311,2.1626,0.189480,0.134660,46.838,1.03460,0.180820,0.113210,0.57607,0.383300,0.40783,1.44230,0.16882,6.0662,0.309150,0.134660,134.470,2.7144,0.39104,0.180820,1.4771,658.7000,0.38385,0.128510,0.167020,0.072354,0.128510,119.96,73.126,0.88223,0.77736,52.568,0.151530,0.107690,1.1669,0.46185,0.36840,0.83251,0.8337,90533.0,0.108990,0.41557,0.89101,0.001422,7.7928,4.9914,119.810,3.0465,3.0560,b'0',False
1,-0.127430,0.46243,0.26917,1.7517,7.597,0.000925,-0.127430,1.16250,1.2944,0.53757,-0.123210,-0.35587,-0.069684,-0.127430,-1871.30,-0.19506,2.1625,-0.127430,-0.098443,67.186,0.65665,-0.080134,-0.098443,NaN,0.089142,-0.19506,-18.99600,0.72207,3.9891,0.347020,-0.095184,92.684,3.9381,3.04930,-0.115680,1.2944,4.8106,0.61842,-0.089372,0.042359,-0.359250,-0.061907,172.59,105.400,-0.53481,1.08630,61.674,-0.117360,-0.090667,1.3564,0.35807,0.25393,1.44210,1.6590,2624.9,-0.089372,-0.23704,1.06250,0.150410,5.4327,3.4629,100.970,3.6150,3.4725,b'0',False
2,0.070488,0.23570,0.52781,3.2393,125.680,0.163670,0.086895,2.87180,1.0574,0.67689,0.086895,0.36866,0.104840,0.086895,725.64,0.50300,4.2426,0.086895,0.076840,51.358,0.99173,0.076618,0.062331,0.20835,0.676890,0.43339,0.71641,2.23180,4.6697,-0.024608,0.076840,80.443,4.5374,0.32506,0.076618,1.2007,NaN,0.67689,0.067752,1.145100,0.071564,0.067752,159.32,107.960,0.44299,2.56420,54.306,0.044954,0.039752,3.2393,0.23570,0.22039,2.86220,2.8622,24672.0,0.054286,0.10413,0.94571,0.000000,7.1070,3.3808,76.076,4.7978,4.7818,b'0',False
3,0.136760,0.40538,0.31543,1.8705,19.115,0.504970,0.136760,1.45390,1.1144,0.58938,0.136760,0.37742,0.106900,0.136760,924.13,0.39496,2.4668,0.136760,0.091304,59.462,1.33550,0.144820,0.091304,0.50497,0.589380,0.39496,1.07750,0.97894,4.3239,0.218650,0.091304,98.398,3.7094,0.35724,0.144820,1.5064,10.0790,0.63242,0.096688,0.218530,0.079248,0.096688,145.87,86.408,0.56046,1.19710,66.263,0.121460,0.081094,1.6719,0.36235,0.26958,1.82910,1.9627,6649.9,0.102630,0.23203,0.89737,0.073024,6.1384,4.2241,88.299,4.1337,4.6484,b'0',False
4,-0.110080,0.69793,0.18878,1.2713,-15.344,0.000000,-0.110080,0.43282,1.7350,0.30207,-0.103100,-0.15820,0.088289,-0.110080,1663.00,0.21948,1.4328,-0.110080,-0.063446,19.414,1.03080,0.000000,-0.063446,NaN,0.230240,0.21948,0.00000,1.63600,3.8426,0.376720,-0.133340,261.350,1.3966,1.39240,0.050620,1.7350,NaN,0.30207,0.029176,0.245800,0.088371,0.000000,150.12,130.710,-1.19280,1.13870,34.660,-0.263260,-0.151730,1.2675,0.69583,0.71602,2.61780,2.6178,1314.0,0.439880,-0.36440,0.57153,0.000000,18.8010,2.7925,146.390,2.4934,15.0360,b'0',False

In [95]:
df.describe()

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,Attr11,Attr12,Attr13,Attr14,Attr15,Attr16,Attr17,Attr18,Attr19,Attr20,Attr21,Attr22,Attr23,Attr24,Attr25,Attr26,Attr27,Attr28,Attr29,Attr30,Attr31,Attr32,Attr33,Attr34,Attr35,Attr36,Attr37,Attr38,Attr39,Attr40,Attr41,Attr42,Attr43,Attr44,Attr45,Attr46,Attr47,Attr48,Attr49,Attr50,Attr51,Attr52,Attr53,Attr54,Attr55,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64
count,9791.000000,9791.000000,9791.000000,9749.000000,9.771000e+03,9791.000000,9791.000000,9773.000000,9792.000000,9791.000000,9791.000000,9749.000000,9771.000000,9791.000000,9.784000e+03,9773.000000,9773.000000,9791.000000,9771.000000,9771.000000,9634.000000,9791.000000,9771.000000,9581.000000,9791.000000,9773.000000,9.151000e+03,9561.000000,9791.000000,9771.000000,9771.000000,9696.000000,9749.000000,9773.000000,9791.000000,9791.000000,5350.000000,9791.000000,9771.000000,9749.000000,9605.000000,9771.000000,9.771000e+03,9.771000e+03,9179.000000,9749.000000,9719.000000,9791.000000,9771.000000,9773.000000,9791.000000,9716.000000,9561.000000,9561.000000,9.792000e+03,9771.000000,9791.000000,9776.000000,9791.000000,9178.000000,9760.000000,9.771000e+03,9749.000000,9561.000000
mean,0.043019,0.596404,0.130959,8.136600,6.465164e+01,-0.059273,0.059446,19.884016,1.882296,0.389040,0.075417,0.210989,0.398902,0.059460,3.017681e+03,0.617918,20.976033,0.064580,-0.019081,62.704589,1.218724,0.066203,-0.070364,0.247742,0.222839,0.451115,1.115883e+03,6.725180,3.946479,5.353531,0.041258,341.625124,8.445313,4.979157,0.058091,2.077261,70.659877,0.487190,-1.072578,3.064235,0.968902,-0.371479,7.356944e+02,6.729892e+02,5.458024,7.274189,112.989701,-0.002370,-0.517222,7.085001,0.469319,10.031638,6.114681,7.402928,7.686330e+03,-0.992263,0.035022,1.133287,0.856053,118.156064,25.194430,2.015157e+03,8.660813,35.949619
std,0.359321,4.587122,4.559074,290.647281,1.475939e+04,6.812754,0.533344,698.697015,17.674650,4.590299,0.528232,74.237274,37.974787,0.533344,1.022731e+05,78.494223,698.757245,0.736143,25.583613,377.204157,5.930840,0.504481,23.889882,8.268015,4.852418,74.037751,3.143938e+04,147.963574,0.865714,340.974268,25.585724,6145.604519,69.690183,58.480776,0.483463,17.341615,621.311292,4.578432,77.056762,87.916989,41.191681,14.174896,3.283705e+04,3.281128e+04,186.414617,290.619843,1993.125597,0.525467,15.737098,287.770829,4.554869,897.307846,90.190534,146.013868,7.605261e+04,77.007971,8.945365,8.038201,26.393305,3230.316692,1099.260821,1.171461e+05,60.838202,483.318623
min,-12.458000,0.000000,-445.910000,-0.045319,-3.794600e+05,-486.820000,-12.458000,-1.848200,-0.032371,-445.910000,-12.244000,-6331.800000,-1460.600000,-12.458000,-1.567500e+06,-6331.800000,0.000857,-12.458000,-1578.700000,0.000000,-1.146300,-12.244000,-1578.700000,-314.370000,-466.340000,-6331.800000,-2.590100e+05,-990.020000,-0.440090,-4940.000000,-1495.600000,0.000000,0.000000,-756.500000,-9.043100,-0.000014,-3.715000,-445.910000,-7522.000000,-8.833300,-1086.800000,-719.800000,-1.158700e+05,-1.158700e+05,-2834.900000,-6.639200,-3.630700,-13.815000,-837.860000,-0.045239,0.000000,0.000000,-1033.700000,-1033.700000,-7.132200e+05,-7522.100000,-597.420000,-30.892000,-284.380000,0.000000,-12.656000,-1.496500e+04,-0.024390,-0.000015
25%,0.001321,0.263145,0.020377,1.047000,-5.121700e+01,-0.000578,0.003004,0.428300,1.006675,0.294440,0.009457,0.007608,0.021204,0.003008,2.173550e+02,0.061874,1.448900,0.003008,0.001937,15.244500,0.920125,0.000000,0.000963,0.004049,0.135600,0.057772,0.000000e+00,0.035097,3.398450,0.082730,0.004434,47.222750,2.702300,0.297400,0.000872,1.030900,1.097050,0.419750,0.000687,0.051234,0.025029,0.000000,6.890100e+01,3.651950e+01,0.010131,0.613890,15.836000,-0.047398,-0.035386,0.768760,0.185285,0.128978,0.684900,0.946990,2.184000e+01,0.003121,0.008768,0.885722,0.000000,5.356325,4.267700,4.323400e+01,2.938800,2.012900
50%,0.041364,0.467740,0.199290,1.591800,-5.557600e-02,0.000000,0.048820,1.088700,1.161300,0.510450,0.062544,0.143690,0.063829,0.048859,9.065550e+02,0.219130,2.134600,0.048859,0.030967,35.657000,1.045700,0.050118,0.025931,0.149150,0.386750,0.199240,1.005500e+00,0.470770,3.976400,0.226950,0.037939,80.884500,4.467900,1.975500,0.046855,1.559400,3.110400,0.613270,0.030427,0.182500,0.089499,0.032384,1.034800e+02,5.786200e+01,0.232560,1.041100,38.482000,0.006990,0.004644,1.230000,0.336680,0.221380,1.211800,1.378300,9.503300e+02,0.043679,0.098026,0.958305,0.002129,9.482000,6.283550,7.472900e+01,4.848900,4.041600
75%,0.111130,0.689255,0.410670,2.880400,5.573200e+01,0.065322,0.126940,2.691000,1.970225,0.714290,0.140805,0.513820,0.127935,0.126960,2.412500e+03,0.599580,3.781500,0.126960,0.083315,65.667500,1.208925,0.126675,0.071692,0.360600,0.614030,0.542190,5.236100e+00,1.570000,4.498550,0.434085,0.093553,133.202500,7.627100,4.509700,0.126375,2.284250,12.239750,0.777415,0.080855,0.666480,0.215980,0.081628,1.481050e+02,8.510950e+01,0.816100,1.971200,70.936000,0.084418,0.051082,2.268800,0.530775,0.364155,2.274200,2.426300,4.694550e+03,0.117170,0.242680,0.996163,0.211790,19.506000,9.938200,1.233450e+02,8.363800,9.413500
max,20.482000,446.910000,22.769000,27146.000000,1.034100e+06,322.200000,38.618000,53209.000000,1704.800000,12.602000,38.618000,3340.900000,2707.700000,38.618000,8.085500e+06,4401.300000,53210.000000,50.266000,1082.600000,26606.000000,396.160000,38.618000,879.860000,400.590000,12.602000,3594.600000,2.037300e+06,11864.000000,9.651800,29526.000000,1083.100000,385590.000000,5534.100000,4260.200000,38.618000,1704.800000,24487.000000,12.602000,112.020000,8007.100000,3443.400000,160.110000,3.020000e+06,3.020000e+06,10337.000000,27146.000000,140990.000000,33.535000,107.680000,27146.000000,446.910000,88433.000000,4784.100000,11678.000000,6.123700e+06,112.020000,226.760000,668.750000,1661.000000,251570.000000,108000.000000,1.077900e+07,5662.400000,21153.000000

In [96]:
sum(df.bankruptcy == True)

515

In [97]:
df2 = df[['Attr1','Attr2','Attr7','Attr10','bankruptcy']]
df2.columns = ['X1','X2','X7','X10','Bankruptcy']

In [98]:
print(df2)

            X1       X2        X7      X10  Bankruptcy
0     0.159290  0.46240  0.189480  0.38330       False
1    -0.127430  0.46243 -0.127430  0.53757       False
2     0.070488  0.23570  0.086895  0.67689       False
3     0.136760  0.40538  0.136760  0.58938       False
4    -0.110080  0.69793 -0.110080  0.30207       False
...        ...      ...       ...      ...         ...
9787  0.004676  0.54949  0.013002  0.43205        True
9788 -0.027610  0.60748 -0.027610  0.33509        True
9789 -0.238290  0.62708 -0.240360  0.17760        True
9790  0.097188  0.75300  0.104280  0.24700        True
9791  0.021416  0.48678  0.027253  0.51267        True

[9792 rows x 5 columns]

In [99]:
from sklearn.preprocessing import Imputer
imr = Imputer(missing_values='NaN',strategy='mean',axis=0)
imr = imr.fit(df2.values)
imputed_data = imr.transform(df2.values)
print(imputed_data)

[[ 0.15929   0.4624    0.18948   0.3833    0.      ]
 [-0.12743   0.46243  -0.12743   0.53757   0.      ]
 [ 0.070488  0.2357    0.086895  0.67689   0.      ]
 ...
 [-0.23829   0.62708  -0.24036   0.1776    1.      ]
 [ 0.097188  0.753     0.10428   0.247     1.      ]
 [ 0.021416  0.48678   0.027253  0.51267   1.      ]]

D:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [100]:
df3 = pd.DataFrame(imputed_data)
df3.columns = ['X1','X2','X7','X10','Bankruptcy']
df3.describe()

                X1           X2           X7          X10   Bankruptcy
count  9792.000000  9792.000000  9792.000000  9792.000000  9792.000000
mean      0.043019     0.596404     0.059446     0.389040     0.052594
std       0.359303     4.586887     0.533317     4.590064     0.223233
min     -12.458000     0.000000   -12.458000  -445.910000     0.000000
25%       0.001322     0.263163     0.003005     0.294510     0.000000
50%       0.041374     0.467770     0.048840     0.510435     0.000000
75%       0.111125     0.689183     0.126930     0.714285     0.000000
max      20.482000   446.910000    38.618000    12.602000     1.000000

In [101]:
df4 = df3[(df3['Bankruptcy']==True)]
df4.describe()

               X1          X2          X7         X10  Bankruptcy
count  515.000000  515.000000  515.000000  515.000000       515.0
mean    -0.068873    0.878355   -0.061538    0.103367         1.0
std      0.568076    1.945596    0.568432    1.946747         0.0
min     -4.050600    0.000357   -4.050600  -39.156000         1.0
25%     -0.145510    0.458885   -0.142590    0.105600         1.0
50%      0.000000    0.671030    0.000490    0.305830         1.0
75%      0.044640    0.882850    0.050749    0.516560         1.0
max      9.803700   40.157000    9.803700    0.999450         1.0

In [102]:
df5 = df3[(df3['Bankruptcy']==False)]
df5.describe()

                X1           X2           X7          X10  Bankruptcy
count  9277.000000  9277.000000  9277.000000  9277.000000      9277.0
mean      0.049231     0.580752     0.066162     0.404899         0.0
std       0.343002     4.689694     0.530524     4.692934         0.0
min     -12.458000     0.000000   -12.458000  -445.910000         0.0
25%       0.003128     0.257220     0.004711     0.306400         0.0
50%       0.043545     0.457500     0.051804     0.519670         0.0
75%       0.113140     0.674850     0.129390     0.721390         0.0
max      20.482000   446.910000    38.618000    12.602000         0.0

In [103]:
import numpy as np
sum((df3.X1<(np.mean(df3.X1)-np.std(df3.X1)))&(df3.X10<(np.mean(df3.X10)-np.std(df3.X10))))

15

In [104]:
sum(df3.Bankruptcy== True)/df3.X1.count()

0.052593954248366014

In [105]:
sum(df4.Bankruptcy== True)/df4.X1.count()

1.0

In [106]:
sum(df5.Bankruptcy== True)/df5.X1.count()

0.0